<a href="https://colab.research.google.com/github/gachet/ad-1-26/blob/main/pandas/ejer-pandas-solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicios Pandas

In [2]:
import pandas as pd

**2.** Imprimir la  vessión pandas

In [3]:
pd.__version__

'2.2.3'

## Cuestiones básicas DataFrame



Nota: recordar importar numpy:
```python
import numpy as np
```

Considerar el siguiente diccionario y la lista  `labels`:


data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


**3.** Crear un  a DataFrame `df` con los datos del diccionario y el índice  `labels`.

In [4]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**4.** Imprimir un resumen del marco creado.

In [5]:
df.info()

# ...or...

df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 700.0+ bytes

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

**5.** Mostrar las 3 primeras filas de `df` de dos formas distintas.

In [ ]:
df.iloc[:3]

# or equivalently

df.head(3)

   animal  age visits  priority
a     cat  2.5      1      True
b     cat  3.0      3      True
c  python  0.5      2     False

**6.** Seleccionar las columnas 'animal' y 'age' del mardo de datos df .

In [ ]:
df.loc['a':'c', ['animal', 'age']]

   animal  age
a     cat  2.5
b     cat  3.0
c  python  0.5

In [ ]:
df.loc['a':'c', ['animal', 'age']]

# or

df[['animal', 'age']]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

**7.** Seleccionar los datos en las filas `[3, 4, 8]` *y* en las columnas `['animal', 'age']`.

In [ ]:
df.loc[df.index[[3, 4, 8]], ['animal', 'age']]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [ ]:
df.loc[df.index[[3, 4, 8]], ['animal', 'age']]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

**8.** Seleccionar sólo las filas donde el numero de visitas es mayor que 2.

In [11]:
a = df.loc[:,'visits']>2
df.loc[a]

  animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no

In [ ]:
df.loc[df['visits'] > 2]

  animal  age visits  priority
b    cat  3.0      3      True
d    dog  NaN      3      True
f    cat  1.5      3     False

**9.** Seleccione las filas donde falta la edad, es decir, es "NaN".

In [ ]:
df.loc[df['age'].isnull()]

  animal  age visits  priority
d    dog  NaN      3      True
h    cat  NaN      1      True

In [ ]:
a=df.loc[:,['animal','age']]
a

   animal  age
a     cat  2.5
b     cat  3.0
c  python  0.5
d     dog  NaN
e     dog  5.0
f     cat  1.5
g  python  4.5
h     cat  NaN
i     dog  7.0
j     dog  3.0

In [ ]:
gatos = df.loc[df.loc[:, 'animal'] == 'cat']
gatos

  animal  age visits  priority
a    cat  2.5      1      True
b    cat  3.0      3      True
f    cat  1.5      3     False
h    cat  NaN      1      True

In [ ]:
resultado = gatos.loc[gatos.loc[:,'age']<3]
resultado

  animal  age visits  priority
a    cat  2.5      1      True
f    cat  1.5      3     False

**10.** Seleccione las filas donde el animal es un cat *y* age es menor a 3 (años.

In [ ]:
df[(df['animal'] == 'cat') & (df['age'] < 3)] # nos da una lista de booleanos

  animal  age visits  priority
a    cat  2.5      1      True
f    cat  1.5      3     False

In [ ]:
df.loc[(df.animal == "cat") & (df.age < 3),
                ['visits', 'priority']]

  visits  priority
a      1      True
f      3     False

**11.** Seleccione las filas donde age esté entre 2 y 4 (inclusive).

In [ ]:
df[df['age'].between(2, 4)]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

**12.** Cambie la edad en la fila 'f' a 1,5.

In [ ]:
df.loc['f', 'age'] = 1.5

**13.** Calcule la suma de todas las visitas en `df` (es decir, el número total de visitas).

In [ ]:
df['visits'].sum()

19

**14.** Calcule la edad media de cada animal diferente en "df".

In [ ]:
df.groupby('animal')['age'].mean()

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

**15.** Agregue una nueva fila 'k' a `df` con los valores que elija para cada columna. Luego elimine esa fila para devolver el DataFrame original.

In [ ]:
df.loc['k'] = [5.5, 'dog', 'no', 2]

# and then deleting the new row...

df = df.drop('k')

**16.** Cuente el número de cada tipo de animal en `df`.

In [ ]:
df['animal'].value_counts()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

**17.** Ordene `df` primero por los valores en 'edad' en orden *descendente*, luego por el valor en la columna 'visitas' en orden *ascendente* (por lo que la fila `i` debe ser la primera y la fila `d` debe ser ser la última).

In [ ]:
df.sort_values(by=['age', 'visits'], ascending=[False, True])

  animal  age visits priority
i    dog  7.0      2       no
e    dog  5.0      2       no
g  snake  4.5      1       no
j    dog  3.0      1       no
b    cat  3.0      3      yes
a    cat  2.5      1      yes
f    cat  1.5      3       no
c  snake  0.5      2       no
h    cat  NaN      1      yes
d    dog  NaN      3      yes

**18.** La columna "prioridad" contiene los valores "tes" y "no". Reemplace esta columna con una columna de valores booleanos: "yes" debe ser "true" y "no" debe ser "Falso".

In [ ]:
df['priority'] = df['priority'].map({'yes': True, 'no': False})

**19.** En la columna "animal", cambie las entradas "snake" a "ptthón".

In [ ]:
df['animal'] = df['animal'].replace('snake', 'python')
df

   animal  age visits  priority
a     cat  2.5      1      True
b     cat  3.0      3      True
c  python  0.5      2     False
d     dog  NaN      3      True
e     dog  5.0      2     False
f     cat  1.5      3     False
g  python  4.5      1     False
h     cat  NaN      1      True
i     dog  7.0      2     False
j     dog  3.0      1     False